# Generated by Django 3.2.9 on 2022-03-02 10:32

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(choices=[('CHOCOLATE FUDGE', 'CHOCOLATE FUDGE'), ('CHOCOLATE MINT', 'CHOCOLATE MINT'), ('CHOCOLATE CHIP', 'CHOCOLATE CHIP'), ('RED VELVET', 'RED VELVET'), ('BLUE VELVET', 'BLUE VELVET'), ('GREEN VELVET', 'GREEN VELVET'), ('VANILLA', 'VANILLA'), ('COFFEE', 'COFFEE'), ('COCONUT', 'COCONUT'), ('GINGER', 'GINGER'), ('ZEBRA', 'ZEBRA'), ('CINNAMON', 'CINNAMON'), ('SPICE', 'SPICE'), ('MARBLE', 'MARBLE'), ('PINA COLADA', 'PINA COLADA'), ('LEMON', 'LEMON'), ('LIME', 'LIME'), ('BANANA', 'BANANA'), ('ORANGE', 'ORANGE'), ('PASSION JUICE', 'PASSION JUICE'), ('BUBBLEGUM', 'BUBBLEGUM'), ('CARROT', 'CARROT'), ('MINT', 'MINT'), ('OREO', 'OREO'), ('CARAMEL', 'CARAMEL'), ('BLUEBERRY', 'BLUEBERRY'), ('STRAWBERRY', 'STRAWBERRY'), ('BUTTER', 'BUTTER'), ('FRUIT', 'FRUIT'), ('BLACK FOREST', 'BLACK FOREST'), ('WHITE FOREST', 'WHITE FOREST'), ('BLUEBERRY FOREST', 'BLUEBERRY FOREST'), ('PASSION FRUIT FOREST', 'PASSION FRUIT FOREST')], default='BROWNIES', max_length=100, null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('review', models.IntegerField(blank=True, default=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256, null=True)),
                ('city', models.CharField(max_length=256, null=True)),
                ('state', models.CharField(max_length=256, null=True)),
                ('zipcode', models.CharField(max_length=256, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=250)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('email', models.EmailField(max_length=256, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderitems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.orderitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
